import { NextResponse } from "next/server";
import { revalidatePath } from "next/cache";
import { requireApiAdmin, requireSupabase } from "@/lib/api-auth";
import { ASSET_IMAGES_BUCKET } from "@/lib/storage";

export const runtime = "nodejs";

// POST   /api/admin/inventory/[id]/image    multipart, field "file"
// DELETE /api/admin/inventory/[id]/image    no body
//
// Single image per asset. Uploading replaces any existing image
// (we delete the old file from the bucket so we don't leak orphan
// blobs). DELETE clears the path and removes the file.
//
// Path convention: assets/<asset-id>/<timestamp>.<ext>
// Stored under the private `asset-images` bucket; clients only ever
// see signed URLs generated by signAssetImageUrl().

const MAX_BYTES = 10 * 1024 * 1024;          // 10 MB — phones can produce 5–8 MB shots
const ALLOWED = new Set([
  "image/jpeg",
  "image/png",
  "image/webp",
]);

function extFor(mime: string): string {
  if (mime === "image/jpeg") return "jpg";
  if (mime === "image/png")  return "png";
  if (mime === "image/webp") return "webp";
  return "bin";
}

type Ctx = { params: { id: string } };

export async function POST(req: Request, { params }: Ctx) {
  const auth = await requireApiAdmin();
  if (auth instanceof NextResponse) return auth;

  const supabase = requireSupabase();
  if (supabase instanceof NextResponse) return supabase;

  let form: FormData;
  try { form = await req.formData(); }
  catch { return NextResponse.json({ error: "Invalid multipart body" }, { status: 400 }); }

  const file = form.get("file");
  if (!(file instanceof File)) {
    return NextResponse.json({ error: "file is required" }, { status: 400 });
  }
  if (file.size === 0) {
    return NextResponse.json({ error: "file is empty" }, { status: 400 });
  }
  if (file.size > MAX_BYTES) {
    return NextResponse.json({ error: `File too large (max ${MAX_BYTES / 1024 / 1024} MB)` }, { status: 413 });
  }
  if (!ALLOWED.has(file.type)) {
    return NextResponse.json({ error: "Unsupported file type — use JPG, PNG, or WebP" }, { status: 415 });
  }

  // Confirm the asset exists + grab the previous image_path so we can
  // delete it after the new upload succeeds (delete-old-on-success
  // pattern: never orphan the new file, never strand the old one).
  const { data: existing, error: loadErr } = await supabase
    .from("assets")
    .select("id, image_path")
    .eq("id", params.id)
    .maybeSingle();

  if (loadErr) {
    console.error("[asset image upload] load", loadErr);
    return NextResponse.json({ error: "Could not load asset" }, { status: 500 });
  }
  if (!existing) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const newPath = `assets/${params.id}/${Date.now()}.${extFor(file.type)}`;
  const buf = Buffer.from(await file.arrayBuffer());

  const { error: uploadErr } = await supabase
    .storage
    .from(ASSET_IMAGES_BUCKET)
    .upload(newPath, buf, {
      contentType: file.type,
      upsert: false,
    });

  if (uploadErr) {
    console.error("[asset image upload] storage", uploadErr);
    return NextResponse.json({ error: "Could not upload" }, { status: 500 });
  }

  const { error: updateErr } = await supabase
    .from("assets")
    .update({ image_path: newPath })
    .eq("id", params.id);

  if (updateErr) {
    // Best-effort rollback — drop the just-uploaded file so we don't
    // leave a blob with no DB pointer.
    await supabase.storage.from(ASSET_IMAGES_BUCKET).remove([newPath]).catch(() => null);
    console.error("[asset image upload] update", updateErr);
    return NextResponse.json({ error: "Could not update asset" }, { status: 500 });
  }

  // Drop the old file (if any) — fire and forget; failure here just
  // means a stale orphan in the bucket, not a user-visible problem.
  if (existing.image_path && existing.image_path !== newPath) {
    supabase.storage.from(ASSET_IMAGES_BUCKET).remove([existing.image_path]).catch(() => null);
  }

  revalidatePath(`/admin/inventory/${params.id}`);
  revalidatePath(`/admin/inventory`);
  return NextResponse.json({ ok: true, image_path: newPath });
}

export async function DELETE(_req: Request, { params }: Ctx) {
  const auth = await requireApiAdmin();
  if (auth instanceof NextResponse) return auth;

  const supabase = requireSupabase();
  if (supabase instanceof NextResponse) return supabase;

  const { data: existing, error: loadErr } = await supabase
    .from("assets")
    .select("id, image_path")
    .eq("id", params.id)
    .maybeSingle();

  if (loadErr) {
    console.error("[asset image delete] load", loadErr);
    return NextResponse.json({ error: "Could not load asset" }, { status: 500 });
  }
  if (!existing) return NextResponse.json({ error: "Not found" }, { status: 404 });
  if (!existing.image_path) {
    // Idempotent — already nothing to delete.
    return NextResponse.json({ ok: true });
  }

  const { error: updateErr } = await supabase
    .from("assets")
    .update({ image_path: null })
    .eq("id", params.id);

  if (updateErr) {
    console.error("[asset image delete] update", updateErr);
    return NextResponse.json({ error: "Could not update asset" }, { status: 500 });
  }

  // Then remove the file. If this fails the asset row is already
  // pointing at no image so the user sees the right state; the orphan
  // gets cleaned up on the next manual housekeeping pass.
  await supabase.storage.from(ASSET_IMAGES_BUCKET).remove([existing.image_path]).catch(() => null);

  revalidatePath(`/admin/inventory/${params.id}`);
  revalidatePath(`/admin/inventory`);
  return NextResponse.json({ ok: true });
}
